org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.9

version=1.0.0
group=de.stefantasie

fabric_api_version=0.155.2+26.1.2
mod_menu_version=18.0.0
cloth_config_version=26.1.154
twelvemonkeys_version=3.12.0
